Search.appendIndex(
    [
                {
            "fqsen": "\\EmbedBuilder\\EmbedBuilder",
            "name": "EmbedBuilder",
            "summary": "",
            "url": "classes/EmbedBuilder-EmbedBuilder.html"
        },                {
            "fqsen": "\\EmbedBuilder\\EmbedBuilderInterface",
            "name": "EmbedBuilderInterface",
            "summary": "",
            "url": "classes/EmbedBuilder-EmbedBuilderInterface.html"
        },                {
            "fqsen": "\\EmbedBuilder\\EmbedBuilderInterface\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "",
            "url": "classes/EmbedBuilder-EmbedBuilderInterface.html#method_new"
        },                {
            "fqsen": "\\EmbedBuilder\\EmbedBuilderInterface\u003A\u003Afill\u0028\u0029",
            "name": "fill",
            "summary": "",
            "url": "classes/EmbedBuilder-EmbedBuilderInterface.html#method_fill"
        },                {
            "fqsen": "\\EmbedBuilder\\EmbedBuilderTrait",
            "name": "EmbedBuilderTrait",
            "summary": "",
            "url": "classes/EmbedBuilder-EmbedBuilderTrait.html"
        },                {
            "fqsen": "\\EmbedBuilder\\EmbedBuilderTrait\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "Creates\u0020an\u0020Embed\u0020object\u0020with\u0020the\u0020specified\u0020footer\u0020and\u0020color.",
            "url": "classes/EmbedBuilder-EmbedBuilderTrait.html#method_new"
        },                {
            "fqsen": "\\EmbedBuilder\\EmbedBuilderTrait\u003A\u003Afill\u0028\u0029",
            "name": "fill",
            "summary": "Fills\u0020an\u0020Embed\u0020object\u0020with\u0020the\u0020provided\u0020fields.",
            "url": "classes/EmbedBuilder-EmbedBuilderTrait.html#method_fill"
        },                {
            "fqsen": "\\EventLogger\\EventLogger",
            "name": "EventLogger",
            "summary": "",
            "url": "classes/EventLogger-EventLogger.html"
        },                {
            "fqsen": "\\EventLogger\\EventLogger\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/EventLogger-EventLogger.html#method___construct"
        },                {
            "fqsen": "\\EventLogger\\EventLogger\u003A\u003A\u0024discord",
            "name": "discord",
            "summary": "",
            "url": "classes/EventLogger-EventLogger.html#property_discord"
        },                {
            "fqsen": "\\EventLogger\\EventLogger\u003A\u003A\u0024events",
            "name": "events",
            "summary": "",
            "url": "classes/EventLogger-EventLogger.html#property_events"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerInterface",
            "name": "EventLoggerInterface",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerInterface.html"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait",
            "name": "EventLoggerTrait",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003AafterConstruct\u0028\u0029",
            "name": "afterConstruct",
            "summary": "This\u0020method\u0020is\u0020called\u0020after\u0020the\u0020constructor.",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_afterConstruct"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003AaddLogChannel\u0028\u0029",
            "name": "addLogChannel",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_addLogChannel"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003AremoveLogGuild\u0028\u0029",
            "name": "removeLogGuild",
            "summary": "Removes\u0020the\u0020log\u0020channel\u0020IDs\u0020associated\u0020with\u0020the\u0020specified\u0020guild\u0020ID.",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_removeLogGuild"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003AgetPartDifferences\u0028\u0029",
            "name": "getPartDifferences",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_getPartDifferences"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003AhandleMessages\u0028\u0029",
            "name": "handleMessages",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_handleMessages"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003Adiff\u0028\u0029",
            "name": "diff",
            "summary": "Get\u0020the\u0020difference\u0020between\u0020two\u0020strings.",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_diff"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003AremoveRedundantProperties\u0028\u0029",
            "name": "removeRedundantProperties",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_removeRedundantProperties"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003AgetDifferences\u0028\u0029",
            "name": "getDifferences",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_getDifferences"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003AarrayRecursiveDiff\u0028\u0029",
            "name": "arrayRecursiveDiff",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_arrayRecursiveDiff"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003AlogEvent\u0028\u0029",
            "name": "logEvent",
            "summary": "Logs\u0020an\u0020event\u0020to\u0020a\u0020specified\u0020Discord\u0020channel.",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_logEvent"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003AgetLogChannelsFromEnv\u0028\u0029",
            "name": "getLogChannelsFromEnv",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_getLogChannelsFromEnv"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003AcreateDefaultEventListeners\u0028\u0029",
            "name": "createDefaultEventListeners",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_createDefaultEventListeners"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003AcreateEventListeners\u0028\u0029",
            "name": "createEventListeners",
            "summary": "Registers\u0020event\u0020listeners\u0020with\u0020the\u0020Discord\u0020client.",
            "url": "classes/EventLogger-EventLoggerTrait.html#method_createEventListeners"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003A\u0024footer",
            "name": "footer",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#property_footer"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003A\u0024discord",
            "name": "discord",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#property_discord"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003A\u0024setup",
            "name": "setup",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#property_setup"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003A\u0024color",
            "name": "color",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#property_color"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003A\u0024log_channel_ids",
            "name": "log_channel_ids",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#property_log_channel_ids"
        },                {
            "fqsen": "\\EventLogger\\EventLoggerTrait\u003A\u003A\u0024event_listeners",
            "name": "event_listeners",
            "summary": "",
            "url": "classes/EventLogger-EventLoggerTrait.html#property_event_listeners"
        },                {
            "fqsen": "\\MessageBuilderHelper\\MessageBuilderHelper",
            "name": "MessageBuilderHelper",
            "summary": "",
            "url": "classes/MessageBuilderHelper-MessageBuilderHelper.html"
        },                {
            "fqsen": "\\MessageBuilderHelper\\MessageBuilderHelperInterface",
            "name": "MessageBuilderHelperInterface",
            "summary": "",
            "url": "classes/MessageBuilderHelper-MessageBuilderHelperInterface.html"
        },                {
            "fqsen": "\\MessageBuilderHelper\\MessageBuilderHelperTrait",
            "name": "MessageBuilderHelperTrait",
            "summary": "",
            "url": "classes/MessageBuilderHelper-MessageBuilderHelperTrait.html"
        },                {
            "fqsen": "\\MessageBuilderHelper\\MessageBuilderHelperTrait\u003A\u003Anew\u0028\u0029",
            "name": "new",
            "summary": "Creates\u0020a\u0020new\u0020MessageBuilder\u0020instance\u0020and\u0020adds\u0020the\u0020provided\u0020embeds\u0020to\u0020it.",
            "url": "classes/MessageBuilderHelper-MessageBuilderHelperTrait.html#method_new"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\EmbedBuilder",
            "name": "EmbedBuilder",
            "summary": "",
            "url": "namespaces/embedbuilder.html"
        },                {
            "fqsen": "\\EventLogger",
            "name": "EventLogger",
            "summary": "",
            "url": "namespaces/eventlogger.html"
        },                {
            "fqsen": "\\MessageBuilderHelper",
            "name": "MessageBuilderHelper",
            "summary": "",
            "url": "namespaces/messagebuilderhelper.html"
        }            ]
);
